### ISSUE TITLE
Anomaly Sorcerer - Missing Files

### ISSUE THREAD

**Issue by bouncer1798** [Deratiseur/DAWAP#1]
I tried installing the anomaly sorcerer with the changed animation but got this error:

Install Component [Anomaly (sorcerer)]?
[N]o, [Q]uit or choose one:
 1] With changed animation: magic elemental
 2] Without changed animation (non-rp)
1

Installing [Anomaly (sorcerer) -> With changed animation: magic elemental] [v6]
Stopping installation because of error.

ERROR Installing [Anomaly (sorcerer) -> With changed animation: magic elemental], rolling back to previous state
Will uninstall   0 files for [DERATS_DAWAP/SETUP-DERATS_DAWAP.TP2] component 7.
Uninstalled      0 files for [DERATS_DAWAP/SETUP-DERATS_DAWAP.TP2] component 7.
ERROR: Sys_error("Derats_Dawap/Sorciers/Anoma/Anoma.tph: No such file or directory")

I looked in the mod directory and there is no Anoma.tph file.

**Comment by bouncer1798** [comment]
Getting other install errors for the Necrophorus and Infuser kits as well. Not sure if I should log these as separate issues. Attached is my setup-derats_dawap.debug file. I am installing on EET.
[SETUP-DERATS_DAWAP.TXT](https://github.com/Deratiseur/DAWAP/files/14474243/SETUP-DERATS_DAWAP.TXT)

**Comment by Deratiseur** [comment]
???? the sorcerer has no changed animation. Should be an error elsewhere.

**Comment by Deratiseur** [comment]
thanks for the txt file :) There were some errors in the english tra file, corrected in version 6.3..

**Comment by Deratiseur** [comment]
Done. Corrected in 6.3. Thanks you for reporting.

**Comment by bouncer1798** [comment]
Working thanks!
