### ISSUE TITLE
Showcase NPCs?

### ISSUE THREAD

**Issue by rubyFeedback** [Deratiseur/DAWAP#2]
Hey there Deratiseur,

My main character is usually berserker-mage, largely because I like the magic system in BG2EE,
but berserker because it simplifies gameplay (e. g. immune to mind flayer).

So my main character is pre-set. Still, I'd like to test a few kits in actual gameplay.

Would you consider adding a few NPCs to this mod here? That way they can be hired into
the party. These showcase-NPCs can initially have no background or quest or item,
just the kit itself. At a later time perhaps more content could be added to the NPCs (or not), but the
primary objective is to test some things of the add-on.

Not all kits need a NPC, so to keep this limited in scope, I suggest showcasing only 1-3 or 2-4,
and perhaps just the more interesting variants. Alternatively (or in addition to that), a script
could autogenerate NPCs based on the kit. While this may be more useful, it is probably also
more work, so my suggestion would be to just add 1-3 NPCs initially without any background,
just so players can get them.

As for where they could be found: for simplicity I would put them where nobody else may spawn,
so perhaps in the first scene (the promenade) and they could be put near a magic shop or 
close to a corner or something like that. An altertnative to this would be to add some special
purpose NPC, perhaps a shop with a few curious items (but not too powerful); and to then add
another option, e. g. to hire one such NPC, against some fee. This may be a bit more elegant,
but, to keep it simple, say, 1-3 NPCs could spawn. Or just one, as the first show-case NPC, and
if this works fine more could be added.

Anyway, thanks for reading this proposal.

**Comment by Deratiseur** [comment]
For what you're asking, there's the perfect mod: Argent77's NPC generator. Or you can use NPCs Enhanced... um, for Everyone. Personally, I always use the latter to make Xan, Neera, Irenicus or Cernd "something else based on Dawap".
